name: Build Cairo Win32 Library

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    strategy:
      matrix:
        arch: [x86, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Meson and Ninja
      run: |
        pip list
        pip install meson ninja

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Configure Meson build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: meson setup build-${{ matrix.arch }} --beckend=vs --buildtype=release --default-library=shared --prefix=C:/cairo-win32-lib/${{ matrix.arch }} --libdir=lib --bindir=bin --cross-file=cross/win32-${{ matrix.arch }}.txt

    - name: Build project
      run: meson compile -C build-${{ matrix.arch }}

    - name: Install project
      run: meson install -C build-${{ matrix.arch }}

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cairo-win32-lib-${{ matrix.arch }}
        path: C:/cairo-win32-lib/${{ matrix.arch }}
